name: TheRock rocRAND math-lib tests

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: ""
      test_runs_on:
        type: string
        default: ""
      platform:
        type: string
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: ""
      test_runs_on:
        type: string
        default: ""
      platform:
        type: string
  push:
    branches:
      - ADHOCBUILD

permissions:
  contents: read

jobs:
  test_rocrand:
    name: "rocRAND math-lib test"
    runs-on: ${{ inputs.test_runs_on }}
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      ARTIFACT_RUN_ID: "${{ inputs.artifact_run_id != '' && inputs.artifact_run_id || github.run_id }}"
      OUTPUT_ARTIFACTS_DIR: ${{ github.workspace }}/build
      THEROCK_BIN_DIR: ${{ github.workspace }}/build/bin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run setup test environment workflow
        uses: './.github/actions/setup_test_environment'
        with:
          ARTIFACT_RUN_ID: ${{ env.ARTIFACT_RUN_ID }}
          AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
          OUTPUT_ARTIFACTS_DIR: ${{ env.OUTPUT_ARTIFACTS_DIR }}
          VENV_DIR: ${{ env.VENV_DIR }}
          FETCH_ARTIFACT_ARGS: "--rand --tests"
          PLATFORM: ${{ inputs.platform }}

      - name: Run rocrand tests
        env:
          TEST_TO_IGNORE: "'rocrand.linking'"  # add more if needed
        run: |
          ctest --test-dir ${THEROCK_BIN_DIR}/rocrand \
            --output-on-failure \
            --parallel 8 \
            --exclude-regex ${TEST_TO_IGNORE}
